[package]
name = "plungle"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3"
csv = "1.1.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.134"
rust_decimal = "1.36"
rust_decimal_macros = "1.36"
