# .github/workflows/build.yml

# build on every commit
on:
    push:
        branches:
        - main
        - gh-actions

jobs:
    release:
        name: release ${{ matrix.target }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - target: x86_64-unknown-linux-gnu
                      os: ubuntu-latest
                      archive: tar.gz
                    - target: windows
                      os: windows-latest
                      archive: zip
        steps:
            - uses: actions/checkout@v4
            - name: Compile
              uses: rust-build/rust-build-action@master
              with:
                    RUSTTARGET: ${{ matrix.target }}
                    ARCHIVE_TYPES: ${{ matrix.archive }}
