# .github/workflows/build.yml

name: Build and Release

on:
    pull_request:
    push:
        branches:
        - main
        - gh-actions

env:
    # Disable incremental compilation for faster from-scratch builds
    CARGO_INCREMENTAL: 0
    CRATE_NAME: plungle
    RUST_BACKTRACE: 1

jobs:
    build:
        name: release ${{ matrix.target }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                platform:
                    - os-name: Linux-x86_64
                      runs-on: ubuntu-24.04
                      target: x86_64-unknown-linux-musl
                    - os-name: Windows-aarch64
                      runs-on: windows-latest
                      target: aarch64-pc-windows-msvc
                      skip-tests: true
                toolchain:
                    - stable

        steps:
            - uses: actions/checkout@v4
            - name: Build binary
              uses: houseabsolute/actions-rust-cross@v1
              with:
                command: "build"
                target: ${{ matrix.platform.target }}
                toolchain: ${{ matrix.toolchain }}
              